### ISSUE TITLE
Broken Tags

### ISSUE THREAD

**Issue by WenXin20** [D0CTOR-ZED/FloorMats#6]
`Minecraft v1.18.1`
`Forge v39.0.79`
`Floor Mats v1.5.1`

The tags `forge:tags/items/creosote` & `floormats:tags/items/opener` are broken. They are both missing the `id: ` identifier in the optional tags.

```
[20:48:20] [Worker-Main-3/ERROR]: Couldn't read tag list forge:creosote from forge:tags/items/creosote.json in data pack floormats-1.18.1-v1.5.1.jar
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 4 column 46 path $.values[0].immersiveengineering:creosote_bucket
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:56) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 4 column 46 path $.values[0].immersiveengineering:creosote_bucket
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:703) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:908) ~[gson-2.8.8.jar%2322!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	... 11 more
[20:48:24] [Worker-Main-3/ERROR]: Couldn't read tag list floormats:opener from floormats:tags/items/opener.json in data pack floormats-1.18.1-v1.5.1.jar
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 6 column 36 path $.values[2].#forge:storage_blocks/iron
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:56) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 6 column 36 path $.values[2].#forge:storage_blocks/iron
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:703) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:908) ~[gson-2.8.8.jar%2322!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.1-20211210.034407-srg.jar%23259!/:?]
	... 11 more
```

**Comment by D0CTOR-ZED** [comment]
Thank you for reporting this.  It is now fixed.
